### PR TITLE
‌

### PR DESCRIPTION
**Pull request by Exorcism0666**

### CODE REVIEW

**Comment by Artuto** [comment]
What's exactly the point of updating it? Has it been tested it works as expected? Is it stable?

**Comment by noahpistilli** [comment]
First off, why are you forking the repo every time you want to do something. Secondly to answer Arturo's question, it came out 2 days ago so we don't really know

**Comment by Artuto** [comment]
Yeah, we likely do not need this.

Please do not open Para just updating dependencies for no reason, we can do that ourselves and there is no point if it doesn't fix anything or improve something.

**Comment by Exorcism0666** [comment]
I'm sorry I didn't respond sooner, because I have class despite that :), Find out more:

https://github.com/bettydreemurr/RiiTag/pull/2

https://github.com/DataDog/dd-trace-js/releases/tag/v1.5.0

**Comment by Peter0x44** [comment]
@bettydreemurr if this was something we actually wanted or needed, we would have done it ourselves. Submitting PRS from a bot is not a proper contribution and a pure waste of time
I also very highly doubt you tested it either.

**Pull request closed without merging**
