### PR TITLE
Standardize Overlay Previews

### LINKED ISSUE #22: Redo Overlay Previews
The previews are currently inconsistent. Just create a consistent preview for different overlays.

### PR DESCRIPTION
**Pull request by TheShadowEevee**
Closes #22.

This PR recreates the overlay previews using a standardized template. I just did this real quick using an alt account to display 0 coins and grabbing the tag.max.png file of the tag.

Template below for future overlays:
`Background: RiiConnect24`
`Flag: RC24`
`Mii: Enabled, Guest C`
`Avatar: Disabled`
`Display Name: Overlay Sample`
`Friend Code / Comments: "*Your tag may look different" (Note: Some overlays had this removed due to it not fitting properly.)`
`Games: "3ds-AXCE;wiiu-AMAE01;wii-RMCE01"`
`Coins: Ideally 0`
`Coin Icon: Overlay Default`
`Font: Overlay Default`

### CODE REVIEW

**Comment by larsenv** [comment]
Did you actually change any of the code? It just looks like you deleted the overlay images.

Having it render the tag with the different overlays on-the-fly would be nice, if that's what you're doing with this :)

**Comment by TheShadowEevee** [comment]
I changed the overlay preview images to be uniform, so they better show the difference between the overlays like mentioned in the above issue. Essentially the previews all look the same other than the overlay now, compared to the previous previews having a variety of different backgrounds, avatars, ect.

It would be nice to dynamically update them but that would require running the renderer everytime a dropdown or text field is changed.

**Review by bendevnull — CHANGES_REQUESTED** [review]
I'm not really a fan of the new sample overlay design, but I like the idea. It was actually on my todo list a while back.

So I feel like the FC should be an actual standardized friend code, for a start. 
Second, there should be more games populating the tag, preferably a full tag worth of games.
Third, there should be a less generic, but still generic Mii being displayed, and perhaps a generic avatar. What can also be done is displaying different samples based on what the user has selected (Ex. Display or hide Mii or Avatar).
And finally, a standardized coin count aside from 0 would do nice. Perhaps the max available for the tag overlay?

The overlays can be dynamically generated on server start, if they don't exist, by using a dummy user data file that can be stored somewhere in the user data folder. Just be sure to work around .gitignore to get that dummy file uploaded to the repo.

Aside from all of that, it's a great idea, and I admire the work you're doing for this project! Thank you for the contributions you've made. If you're interested in access to the development server, I can provide you access so you can view pushed changes on a site of yours and allow the rest of the team to view them too. I'll write a RiiTag Updater script that will continuously run and pull commits, then restart the server once a forked repo is pushed to.

That's all from me for now, though. Thank you for your time and contributions, again!

**Comment by bendevnull** [comment]
And a side note too, @TheShadowEevee, I can add you to the Trello board so you can see my other planned ideas for RiiTag. Just let me know either here, or on Discord at bendevnull#1417

**Pull request closed without merging**
